# Generated by Django 4.2.11 on 2026-04-12 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Photo')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('position', models.CharField(max_length=200, verbose_name='Poste')),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('FREELANCE', 'Freelance')], default='CDI', max_length=20, verbose_name='Type de contrat')),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('CONGE', 'En congé')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('hire_date', models.DateField(verbose_name="Date d'embauche")),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx'), models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'), models.Index(fields=['department'], name='employees_e_departm_99b42d_idx'), models.Index(fields=['status'], name='employees_e_status_61c2f6_idx')],
            },
        ),
    ]
